let categories = [
    'bird',
    'car',
    'tech',
    'app',
    'instrument',
    'sports',
    'Crested Auklet',
    'Great Auk',
    'Japanese Murrelet',
    'Little Auk',
    'dental floss',
    'clock',
    'owl',
    'duck',
    'woodpecker',
    'violin',
    'boulevard',
    'christ the redeemer',
    'stop',
    'start',
    'table',
    'wood',
    'cricket',
    'fence',
    'Razorbill',
    'Tufted Puffin',
    'aerofit',
    'dictionary',
    'computer science',
    'science',
    'mouth',
    'ophthalmologist',
    'orthopedist'
];

module.exports = categories;